// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kuvalkin/gophkeeper/internal/server/service/entry (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=./entry_service_mock.go -package=mocks -mock_names Service=MockEntryService github.com/kuvalkin/gophkeeper/internal/server/service/entry Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"

	entry "github.com/kuvalkin/gophkeeper/internal/server/service/entry"
	gomock "go.uber.org/mock/gomock"
)

// MockEntryService is a mock of Service interface.
type MockEntryService struct {
	ctrl     *gomock.Controller
	recorder *MockEntryServiceMockRecorder
	isgomock struct{}
}

// MockEntryServiceMockRecorder is the mock recorder for MockEntryService.
type MockEntryServiceMockRecorder struct {
	mock *MockEntryService
}

// NewMockEntryService creates a new mock instance.
func NewMockEntryService(ctrl *gomock.Controller) *MockEntryService {
	mock := &MockEntryService{ctrl: ctrl}
	mock.recorder = &MockEntryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEntryService) EXPECT() *MockEntryServiceMockRecorder {
	return m.recorder
}

// DeleteEntry mocks base method.
func (m *MockEntryService) DeleteEntry(ctx context.Context, userID, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEntry", ctx, userID, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntry indicates an expected call of DeleteEntry.
func (mr *MockEntryServiceMockRecorder) DeleteEntry(ctx, userID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntry", reflect.TypeOf((*MockEntryService)(nil).DeleteEntry), ctx, userID, key)
}

// GetEntry mocks base method.
func (m *MockEntryService) GetEntry(ctx context.Context, userID, key string) (entry.Metadata, io.ReadCloser, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntry", ctx, userID, key)
	ret0, _ := ret[0].(entry.Metadata)
	ret1, _ := ret[1].(io.ReadCloser)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetEntry indicates an expected call of GetEntry.
func (mr *MockEntryServiceMockRecorder) GetEntry(ctx, userID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntry", reflect.TypeOf((*MockEntryService)(nil).GetEntry), ctx, userID, key)
}

// SetEntry mocks base method.
func (m *MockEntryService) SetEntry(ctx context.Context, userID string, md entry.Metadata, overwrite bool) (chan<- entry.UploadChunk, <-chan entry.SetEntryResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetEntry", ctx, userID, md, overwrite)
	ret0, _ := ret[0].(chan<- entry.UploadChunk)
	ret1, _ := ret[1].(<-chan entry.SetEntryResult)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SetEntry indicates an expected call of SetEntry.
func (mr *MockEntryServiceMockRecorder) SetEntry(ctx, userID, md, overwrite any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetEntry", reflect.TypeOf((*MockEntryService)(nil).SetEntry), ctx, userID, md, overwrite)
}
