// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kuvalkin/gophkeeper/internal/server/service/user (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=./user_service_mock.go -package=mocks -mock_names Service=MockUserService github.com/kuvalkin/gophkeeper/internal/server/service/user Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	user "github.com/kuvalkin/gophkeeper/internal/server/service/user"
	gomock "go.uber.org/mock/gomock"
)

// MockUserService is a mock of Service interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// LoginUser mocks base method.
func (m *MockUserService) LoginUser(ctx context.Context, login, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", ctx, login, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockUserServiceMockRecorder) LoginUser(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockUserService)(nil).LoginUser), ctx, login, password)
}

// ParseAuthToken mocks base method.
func (m *MockUserService) ParseAuthToken(ctx context.Context, token string) (*user.TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseAuthToken", ctx, token)
	ret0, _ := ret[0].(*user.TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseAuthToken indicates an expected call of ParseAuthToken.
func (mr *MockUserServiceMockRecorder) ParseAuthToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseAuthToken", reflect.TypeOf((*MockUserService)(nil).ParseAuthToken), ctx, token)
}

// RegisterUser mocks base method.
func (m *MockUserService) RegisterUser(ctx context.Context, login, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, login, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockUserServiceMockRecorder) RegisterUser(ctx, login, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockUserService)(nil).RegisterUser), ctx, login, password)
}
