-- +goose Up
CREATE TABLE IF NOT EXISTS entries (
    key TEXT PRIMARY KEY NOT NULL,
    name TEXT NOT NULL,
    notes BLOB DEFAULT NULL,
    version INTEGER NOT NULL DEFAULT 1,
    is_downloaded BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS accounts (
    name TEXT PRIMARY KEY NOT NULL,
    token BLOB DEFAULT NULL,
    version INTEGER DEFAULT NULL
);

-- +goose Down
DROP TABLE IF EXISTS entries;
DROP TABLE IF EXISTS accounts;