// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kuvalkin/gophkeeper/internal/server/service/entry (interfaces: MetadataRepository)
//
// Generated by this command:
//
//	mockgen -destination=./internal/server/service/entry/meta_repository_mock_test.go -package=entry_test github.com/kuvalkin/gophkeeper/internal/server/service/entry MetadataRepository
//

// Package entry_test is a generated GoMock package.
package entry_test

import (
	context "context"
	reflect "reflect"

	entry "github.com/kuvalkin/gophkeeper/internal/server/service/entry"
	gomock "go.uber.org/mock/gomock"
)

// MockMetadataRepository is a mock of MetadataRepository interface.
type MockMetadataRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMetadataRepositoryMockRecorder
	isgomock struct{}
}

// MockMetadataRepositoryMockRecorder is the mock recorder for MockMetadataRepository.
type MockMetadataRepositoryMockRecorder struct {
	mock *MockMetadataRepository
}

// NewMockMetadataRepository creates a new mock instance.
func NewMockMetadataRepository(ctrl *gomock.Controller) *MockMetadataRepository {
	mock := &MockMetadataRepository{ctrl: ctrl}
	mock.recorder = &MockMetadataRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetadataRepository) EXPECT() *MockMetadataRepositoryMockRecorder {
	return m.recorder
}

// DeleteMetadata mocks base method.
func (m *MockMetadataRepository) DeleteMetadata(ctx context.Context, userID, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMetadata", ctx, userID, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMetadata indicates an expected call of DeleteMetadata.
func (mr *MockMetadataRepositoryMockRecorder) DeleteMetadata(ctx, userID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).DeleteMetadata), ctx, userID, key)
}

// GetMetadata mocks base method.
func (m *MockMetadataRepository) GetMetadata(ctx context.Context, userID, key string) (entry.Metadata, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMetadata", ctx, userID, key)
	ret0, _ := ret[0].(entry.Metadata)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMetadata indicates an expected call of GetMetadata.
func (mr *MockMetadataRepositoryMockRecorder) GetMetadata(ctx, userID, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).GetMetadata), ctx, userID, key)
}

// SetMetadata mocks base method.
func (m *MockMetadataRepository) SetMetadata(ctx context.Context, userID string, md entry.Metadata) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMetadata", ctx, userID, md)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMetadata indicates an expected call of SetMetadata.
func (mr *MockMetadataRepositoryMockRecorder) SetMetadata(ctx, userID, md any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMetadata", reflect.TypeOf((*MockMetadataRepository)(nil).SetMetadata), ctx, userID, md)
}
