// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: api/proto/serialize/v1/serialize.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Login struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Login) Reset() {
	*x = Login{}
	mi := &file_api_proto_serialize_v1_serialize_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_serialize_v1_serialize_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_api_proto_serialize_v1_serialize_proto_rawDescGZIP(), []int{0}
}

func (x *Login) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *Login) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type BankCard struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	Number         string                   `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	ExpirationDate *BankCard_ExpirationDate `protobuf:"bytes,2,opt,name=expiration_date,json=expirationDate,proto3" json:"expiration_date,omitempty"`
	HolderName     string                   `protobuf:"bytes,3,opt,name=holder_name,json=holderName,proto3" json:"holder_name,omitempty"`
	// cvv is a 3 or 4 digit number
	Cvv           int32 `protobuf:"zigzag32,4,opt,name=cvv,proto3" json:"cvv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCard) Reset() {
	*x = BankCard{}
	mi := &file_api_proto_serialize_v1_serialize_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCard) ProtoMessage() {}

func (x *BankCard) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_serialize_v1_serialize_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCard.ProtoReflect.Descriptor instead.
func (*BankCard) Descriptor() ([]byte, []int) {
	return file_api_proto_serialize_v1_serialize_proto_rawDescGZIP(), []int{1}
}

func (x *BankCard) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *BankCard) GetExpirationDate() *BankCard_ExpirationDate {
	if x != nil {
		return x.ExpirationDate
	}
	return nil
}

func (x *BankCard) GetHolderName() string {
	if x != nil {
		return x.HolderName
	}
	return ""
}

func (x *BankCard) GetCvv() int32 {
	if x != nil {
		return x.Cvv
	}
	return 0
}

type BankCard_ExpirationDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          int32                  `protobuf:"zigzag32,1,opt,name=year,proto3" json:"year,omitempty"`
	Month         int32                  `protobuf:"zigzag32,2,opt,name=month,proto3" json:"month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankCard_ExpirationDate) Reset() {
	*x = BankCard_ExpirationDate{}
	mi := &file_api_proto_serialize_v1_serialize_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankCard_ExpirationDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankCard_ExpirationDate) ProtoMessage() {}

func (x *BankCard_ExpirationDate) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_serialize_v1_serialize_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankCard_ExpirationDate.ProtoReflect.Descriptor instead.
func (*BankCard_ExpirationDate) Descriptor() ([]byte, []int) {
	return file_api_proto_serialize_v1_serialize_proto_rawDescGZIP(), []int{1, 0}
}

func (x *BankCard_ExpirationDate) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *BankCard_ExpirationDate) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

var File_api_proto_serialize_v1_serialize_proto protoreflect.FileDescriptor

var file_api_proto_serialize_v1_serialize_proto_rawDesc = string([]byte{
	0x0a, 0x26, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x69,
	0x61, 0x6c, 0x69, 0x7a, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69,
	0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2a, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x75,
	0x76, 0x61, 0x6c, 0x6b, 0x69, 0x6e, 0x2e, 0x67, 0x6f, 0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x62, 0x75, 0x66, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61,
	0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x51, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x20, 0x0a, 0x05, 0x6c, 0x6f,
	0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a, 0xba, 0x48, 0x07, 0xc8, 0x01,
	0x01, 0x72, 0x02, 0x10, 0x01, 0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x26, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x0a,
	0xba, 0x48, 0x07, 0xc8, 0x01, 0x01, 0x72, 0x02, 0x10, 0x01, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73,
	0x77, 0x6f, 0x72, 0x64, 0x22, 0xce, 0x02, 0x0a, 0x08, 0x42, 0x61, 0x6e, 0x6b, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x22, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x42, 0x0a, 0xba, 0x48, 0x07, 0xc8, 0x01, 0x01, 0x72, 0x02, 0x10, 0x01, 0x52, 0x06, 0x6e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x74, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x43,
	0x2e, 0x63, 0x6f, 0x6d, 0x2e, 0x6b, 0x75, 0x76, 0x61, 0x6c, 0x6b, 0x69, 0x6e, 0x2e, 0x67, 0x6f,
	0x70, 0x68, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x73,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x6e, 0x6b,
	0x43, 0x61, 0x72, 0x64, 0x2e, 0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44,
	0x61, 0x74, 0x65, 0x42, 0x06, 0xba, 0x48, 0x03, 0xc8, 0x01, 0x01, 0x52, 0x0e, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x2b, 0x0a, 0x0b, 0x68,
	0x6f, 0x6c, 0x64, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x42, 0x0a, 0xba, 0x48, 0x07, 0xc8, 0x01, 0x01, 0x72, 0x02, 0x10, 0x01, 0x52, 0x0a, 0x68, 0x6f,
	0x6c, 0x64, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x63, 0x76, 0x76, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x11, 0x42, 0x0f, 0xba, 0x48, 0x0c, 0xc8, 0x01, 0x01, 0x3a, 0x07, 0x18,
	0x9e, 0x9c, 0x01, 0x28, 0xc8, 0x01, 0x52, 0x03, 0x63, 0x76, 0x76, 0x1a, 0x58, 0x0a, 0x0e, 0x45,
	0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a,
	0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x11, 0x42, 0x0e, 0xba, 0x48, 0x0b,
	0xc8, 0x01, 0x01, 0x3a, 0x06, 0x10, 0xf0, 0x2e, 0x20, 0xa0, 0x1f, 0x52, 0x04, 0x79, 0x65, 0x61,
	0x72, 0x12, 0x22, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x11,
	0x42, 0x0c, 0xba, 0x48, 0x09, 0xc8, 0x01, 0x01, 0x3a, 0x04, 0x18, 0x18, 0x28, 0x02, 0x52, 0x05,
	0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x42, 0x20, 0x5a, 0x1e, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a,
	0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_proto_serialize_v1_serialize_proto_rawDescOnce sync.Once
	file_api_proto_serialize_v1_serialize_proto_rawDescData []byte
)

func file_api_proto_serialize_v1_serialize_proto_rawDescGZIP() []byte {
	file_api_proto_serialize_v1_serialize_proto_rawDescOnce.Do(func() {
		file_api_proto_serialize_v1_serialize_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_serialize_v1_serialize_proto_rawDesc), len(file_api_proto_serialize_v1_serialize_proto_rawDesc)))
	})
	return file_api_proto_serialize_v1_serialize_proto_rawDescData
}

var file_api_proto_serialize_v1_serialize_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_serialize_v1_serialize_proto_goTypes = []any{
	(*Login)(nil),                   // 0: com.kuvalkin.gophkeeper.proto.serialize.v1.Login
	(*BankCard)(nil),                // 1: com.kuvalkin.gophkeeper.proto.serialize.v1.BankCard
	(*BankCard_ExpirationDate)(nil), // 2: com.kuvalkin.gophkeeper.proto.serialize.v1.BankCard.ExpirationDate
}
var file_api_proto_serialize_v1_serialize_proto_depIdxs = []int32{
	2, // 0: com.kuvalkin.gophkeeper.proto.serialize.v1.BankCard.expiration_date:type_name -> com.kuvalkin.gophkeeper.proto.serialize.v1.BankCard.ExpirationDate
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_serialize_v1_serialize_proto_init() }
func file_api_proto_serialize_v1_serialize_proto_init() {
	if File_api_proto_serialize_v1_serialize_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_serialize_v1_serialize_proto_rawDesc), len(file_api_proto_serialize_v1_serialize_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_serialize_v1_serialize_proto_goTypes,
		DependencyIndexes: file_api_proto_serialize_v1_serialize_proto_depIdxs,
		MessageInfos:      file_api_proto_serialize_v1_serialize_proto_msgTypes,
	}.Build()
	File_api_proto_serialize_v1_serialize_proto = out.File
	file_api_proto_serialize_v1_serialize_proto_goTypes = nil
	file_api_proto_serialize_v1_serialize_proto_depIdxs = nil
}
