// Code generated by MockGen. DO NOT EDIT.
// Source: google.golang.org/grpc (interfaces: ServerStreamingServer)
//
// Generated by this command:
//
//	mockgen -destination=./internal/server/transport/servers/entry/server_stream_mock_test.go -package=entry_test google.golang.org/grpc ServerStreamingServer
//

// Package entry_test is a generated GoMock package.
package entry_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	metadata "google.golang.org/grpc/metadata"
)

// MockServerStreamingServer is a mock of ServerStreamingServer interface.
type MockServerStreamingServer[Res any] struct {
	ctrl     *gomock.Controller
	recorder *MockServerStreamingServerMockRecorder[Res]
	isgomock struct{}
}

// MockServerStreamingServerMockRecorder is the mock recorder for MockServerStreamingServer.
type MockServerStreamingServerMockRecorder[Res any] struct {
	mock *MockServerStreamingServer[Res]
}

// NewMockServerStreamingServer creates a new mock instance.
func NewMockServerStreamingServer[Res any](ctrl *gomock.Controller) *MockServerStreamingServer[Res] {
	mock := &MockServerStreamingServer[Res]{ctrl: ctrl}
	mock.recorder = &MockServerStreamingServerMockRecorder[Res]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServerStreamingServer[Res]) EXPECT() *MockServerStreamingServerMockRecorder[Res] {
	return m.recorder
}

// Context mocks base method.
func (m *MockServerStreamingServer[Res]) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockServerStreamingServerMockRecorder[Res]) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).Context))
}

// RecvMsg mocks base method.
func (m_2 *MockServerStreamingServer[Res]) RecvMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "RecvMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecvMsg indicates an expected call of RecvMsg.
func (mr *MockServerStreamingServerMockRecorder[Res]) RecvMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecvMsg", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).RecvMsg), m)
}

// Send mocks base method.
func (m *MockServerStreamingServer[Res]) Send(arg0 *Res) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockServerStreamingServerMockRecorder[Res]) Send(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).Send), arg0)
}

// SendHeader mocks base method.
func (m *MockServerStreamingServer[Res]) SendHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendHeader indicates an expected call of SendHeader.
func (mr *MockServerStreamingServerMockRecorder[Res]) SendHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendHeader", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).SendHeader), arg0)
}

// SendMsg mocks base method.
func (m_2 *MockServerStreamingServer[Res]) SendMsg(m any) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "SendMsg", m)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMsg indicates an expected call of SendMsg.
func (mr *MockServerStreamingServerMockRecorder[Res]) SendMsg(m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMsg", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).SendMsg), m)
}

// SetHeader mocks base method.
func (m *MockServerStreamingServer[Res]) SetHeader(arg0 metadata.MD) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeader", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeader indicates an expected call of SetHeader.
func (mr *MockServerStreamingServerMockRecorder[Res]) SetHeader(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeader", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).SetHeader), arg0)
}

// SetTrailer mocks base method.
func (m *MockServerStreamingServer[Res]) SetTrailer(arg0 metadata.MD) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetTrailer", arg0)
}

// SetTrailer indicates an expected call of SetTrailer.
func (mr *MockServerStreamingServerMockRecorder[Res]) SetTrailer(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTrailer", reflect.TypeOf((*MockServerStreamingServer[Res])(nil).SetTrailer), arg0)
}
