// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kuvalkin/gophkeeper/internal/storage/blob (interfaces: Repository)
//
// Generated by this command:
//
//	mockgen -destination=./blob_repository_mock_test.go -package=entry_test github.com/kuvalkin/gophkeeper/internal/storage/blob Repository
//

// Package entry_test is a generated GoMock package.
package entry_test

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DeleteBlob mocks base method.
func (m *MockRepository) DeleteBlob(key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBlob", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBlob indicates an expected call of DeleteBlob.
func (mr *MockRepositoryMockRecorder) DeleteBlob(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBlob", reflect.TypeOf((*MockRepository)(nil).DeleteBlob), key)
}

// OpenBlobReader mocks base method.
func (m *MockRepository) OpenBlobReader(key string) (io.ReadCloser, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenBlobReader", key)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// OpenBlobReader indicates an expected call of OpenBlobReader.
func (mr *MockRepositoryMockRecorder) OpenBlobReader(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenBlobReader", reflect.TypeOf((*MockRepository)(nil).OpenBlobReader), key)
}

// OpenBlobWriter mocks base method.
func (m *MockRepository) OpenBlobWriter(key string) (io.WriteCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenBlobWriter", key)
	ret0, _ := ret[0].(io.WriteCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenBlobWriter indicates an expected call of OpenBlobWriter.
func (mr *MockRepositoryMockRecorder) OpenBlobWriter(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenBlobWriter", reflect.TypeOf((*MockRepository)(nil).OpenBlobWriter), key)
}
